# Arithmetic Functions

# Shuffle
# unique
# Resize
# Flatten
# Ravel

In [1]:
import numpy as np
var = np.array([1,2,3,5,6])

np.random.shuffle(var)
print(var)

[3 6 1 2 5]


In [2]:
var1 = np.array([2,4,5,6,8,6,3,2,4])

x = np.unique(var1,return_index=True,return_counts=True)

print(x)

(array([2, 3, 4, 5, 6, 8]), array([0, 6, 1, 2, 3, 4], dtype=int64), array([2, 1, 2, 1, 2, 1], dtype=int64))


In [3]:
var2 = np.array([1,3,4,5,6,7,8])
y = np.resize(var2,(2,3))
print(y)

[[1 3 4]
 [5 6 7]]
