# Arithmetic Operation In NumPy Array

# a + b  np.add(a,b), a - b np.subtract(a,b), a * b np.multiply(a,b), a/b   np.divide(a,b), a % b np.mod(a,b), a**b np.power(a,b), 1/a   np.recipocal(a)

In [1]:
import numpy as np

var = np.array([1,2,3,5])
varadd = var + 3
print(varadd)

[4 5 6 8]


In [2]:
import numpy as np

var = np.array([1,2,3,5])
var1 = np.array([3,5,6,7])
varadd = var + var1
print(varadd)

[ 4  7  9 12]


In [4]:
var = np.array([1,2,3,5])
var1 = np.array([3,5,6,7])
varadd = var1 - var
print(varadd)

[2 3 3 2]


In [5]:
var = np.array([2,4,6,7])
varmod = var % 3
print(varmod)

[2 1 0 1]


In [6]:
var = np.array([2,4,6,7])
varmod = var / 3
print(varmod)

[0.66666667 1.33333333 2.         2.33333333]


In [8]:
var2 = np.array([1,2,4,5])
var3 = np.array([5,6,7,8])
varadd1 = np.add(var3,3)
print(varadd1)

[ 8  9 10 11]
