# Create Numpy Array with Random Numbers Function

# Rand()  range alie between 0 to 1

In [3]:
import numpy as np

var = np.random.rand(4)
print(var)

[0.33645236 0.53027001 0.23728094 0.91519622]


In [4]:
val1 = np.random.rand(2,5)
print(val1)

[[0.94413458 0.03923974 0.28036267 0.1150668  0.50787877]
 [0.53992636 0.21711053 0.50680603 0.6960874  0.97740627]]


# Randn() close to 0 this may return positive and negative numbers

In [5]:
var2 = np.random.randn(5)
print(var2)

[-0.22772097 -1.66974348 -0.27992138 -1.47589629 -0.66366022]


In [6]:
var3 = np.random.randn(2,5)
print(var3)

[[-1.32607861 -0.56271086  1.72295875  1.29753293 -1.36866241]
 [ 0.77600819 -0.14301094  0.68488712  0.19111101 -1.01504233]]


# Ranf() fill with random floats in halfopen interval [0.0, 1.0)

In [7]:
var4 = np.random.ranf(4)
print(var4)

[0.69754992 0.77644021 0.46986522 0.85927246]


In [9]:
var5 = np.random.ranf(6)
print(var5)

[0.73449071 0.59457096 0.26176568 0.82377239 0.76341564 0.68799305]


# Randit() the function to be generate random number in a given range var5 = np.random.randint(min,max,total_values)

In [11]:
var5 = np.random.randint(5,50, 10)
print(var5)

[ 8 36 49 49 37 14 46 32 21 41]
