# Data Type

In [2]:
import numpy as np

var = np.array([1,3,5,6])

print(var)
print("Data type",var.dtype)


[1 3 5 6]
Data type int32


In [3]:
var1 = np.array([0, 1.0,5,8])
print(var1)
print("Data type",var1.dtype)

[0. 1. 5. 8.]
Data type float64


In [5]:
var2 = np.array(["A", "S", "D", "G"])
print(var2)
print("Data type", var2.dtype)

['A' 'S' 'D' 'G']
Data type <U1


In [7]:
x = np.array([1,2,3,4,5],dtype = np.int8)
print("Data type: ",x.dtype)
print(x)

Data type:  int8
[1 2 3 4 5]


In [11]:
x1 = np.array([1,2,3,4,5],dtype = "f")
print("Data type: ",x1.dtype)
print(x1)

Data type:  float32
[1. 2. 3. 4. 5.]


# Conversion of data Type

In [14]:
y = np.array([1,2,3,5,6])
new = np.float32(y)
new_one = np.int_(new)

print("Data type : ",y.dtype)
print("Data type: ",new.dtype)
print("Data type: ", new_one.dtype)

print(y)
print(new)
print(new_one)

Data type :  int32
Data type:  float32
Data type:  int32
[1 2 3 5 6]
[1. 2. 3. 5. 6.]
[1 2 3 5 6]
