# Indexing And Slicing In NumPy Arrray

# Indexing

In [4]:
import numpy as np
var = np.array([9,4,5,6])
print(var[1])
print(var[-2])

4
5


In [7]:
var1 = np.array([[[1,2],[6,7]]])
print(var1)
print(var1.ndim)
print()
print(var1[0,1,1])

[[[1 2]
  [6 7]]]
3

7


# Slicing Of Array (Start : stop : step)

In [18]:
var2  = np.array([1,2,3,5,6,7,8])
                # 0,1,2,3,4,5,6

print(var2)
print()
print("2 to 6",var2[1:4])
print()
print("2 to end",var2[1:])
print()
print("start to 5",var2[:5])

print("Stop :",var[1:6:2])

[1 2 3 5 6 7 8]

2 to 6 [2 3 5]

2 to end [2 3 5 6 7 8]

start to 5 [1 2 3 5 6]
Stop : [4 6]


In [22]:
var3 = np.array([[1,3,5,6,9,8],[11,22,44,55,66,88],[23,31,43,53,65,67]])
print(var3)

print()

print("22 to 88 :",var3[1,1:])

[[ 1  3  5  6  9  8]
 [11 22 44 55 66 88]
 [23 31 43 53 65 67]]

22 to 88 : [22 44 55 66 88]
