# Iteration

In [1]:
import numpy as np

In [3]:
var = np.array([3,4,5,7,8])
print(var)
print()
for i in var:
    print(i)

[3 4 5 7 8]

3
4
5
7
8


In [9]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
for j in var1:
    print(j)
    
print()
for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4
