# Join Array

In [4]:
import numpy as np
var = np.array([1,2,3,4])
var1 = np.array([2,3,4,5])
res = np.concatenate((var,var1))
print(res)

[1 2 3 4 2 3 4 5]


In [6]:
var2 = np.array([[1,2],[3,4]])
var3 = np.array([[9,8],[7,6]])

ar_new = np.concatenate((var2,var3),axis=1)

print(var1)
print()
print(var2)
print()
print(ar_new)

[2 3 4 5]

[[1 2]
 [3 4]]

[[1 2 9 8]
 [3 4 7 6]]


In [11]:
var4 = np.array([1,2,3,4])
var5 = np.array([9,8,7,6])

a_new = np.stack((var4,var5),axis = 0)
a_new1 = np.hstack((var4,var5)) # row
a_new2 = np.vstack((var4,var5)) # height
a_new3 = np.dstack((var4,var5))

print(a_new)
print()
print(a_new1)
print()
print(a_new2)
print()
print(a_new3)


[[1 2 3 4]
 [9 8 7 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


# Split Array

In [12]:
arr = np.array([1,2,3,5,6])
print(arr)

arr_1 = np.array_split(arr,3)
print()
print(arr_1)

[1 2 3 5 6]

[array([1, 2]), array([3, 5]), array([6])]


In [17]:
arr1 = np.array([[1,2,3,5,6,2],[3,4,5,6,9,7]])
print(arr1)

print()
arr_res = np.array_split(arr1,3)
arr_res1 = np.array_split(arr1,3, axis=1)


print(arr_res)
print()
print(arr_res1)


[[1 2 3 5 6 2]
 [3 4 5 6 9 7]]

[array([[1, 2, 3, 5, 6, 2]]), array([[3, 4, 5, 6, 9, 7]]), array([], shape=(0, 6), dtype=int32)]

[array([[1, 2],
       [3, 4]]), array([[3, 5],
       [5, 6]]), array([[6, 2],
       [9, 7]])]
