# NUMPY ARRAY

# import libraries

In [1]:
import numpy as np

# create numpy array

In [2]:
a = np.array([1,2,3,5,6])
print(a)

[1 2 3 5 6]


# Array

In [3]:
x=[1,2,3,4,5,6]
y=np.array(x)

In [4]:
print(y)

[1 2 3 4 5 6]


In [5]:
print(type(y))

<class 'numpy.ndarray'>


# Dimension in array

# 1D Array

In [6]:
x=[1,2,3,4,5,6]

y=np.array(x)
print(y)

print(y.ndim)
print(type(y))

[1 2 3 4 5 6]
1
<class 'numpy.ndarray'>


# 2D array

In [8]:
array1=np.array([[1,2,3,4],[4,5,6,7]])
print(array1)

print(array1.ndim)
print(type(array1))

[[1 2 3 4]
 [4 5 6 7]]
2
<class 'numpy.ndarray'>


# 3D array

In [9]:
array2=np.array([[[1,2,3,4],[1,4,5,6],[4,5,6,7]]])
print(array2)
print(array2.ndim)

[[[1 2 3 4]
  [1 4 5 6]
  [4 5 6 7]]]
3


# ND array

In [10]:
arrayn=np.array([1,2,3,4],ndmin=10)
print(arrayn)
print(arrayn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# SPECIAL NUMPY ARRAY

# ARRAY FILL WITH ZERO

In [13]:
array_zero = np.zeros(5)
print(array_zero)
print(array_zero.ndim)
print(type(array_zero))

[0. 0. 0. 0. 0.]
1
<class 'numpy.ndarray'>


In [14]:
array_zero1=np.zeros((3,4))
print (array_zero1)
print(array_zero1.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


# ARRAY FILL WITH ONES

In [17]:
array_one=np.ones(5)
print(array_one)
print(array_one.ndim)

[1. 1. 1. 1. 1.]
1


In [18]:
array_one=np.ones([3,4])
print(array_one)

print(array_one.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2


In [19]:
array_one=np.ones([2,2])
print(array_one)

[[1. 1.]
 [1. 1.]]


# ARRAY FILL WITH EMPTY

In [20]:
array_em=np.empty(4)
print(array_em)

[1. 1. 1. 1.]


# ARRAY FILL WITH RANGE

In [21]:
array_ra=np.arange(4)
print(array_ra)

[0 1 2 3]


In [22]:
array_ra1= np.arange(5)
print(array_ra1)

[0 1 2 3 4]


# ARRAY FILL WITH DIAGONAL

In [23]:
array_dia=np.eye(4)
print(array_dia)
print(array_dia.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
2


In [24]:
array_dia1=np.eye(3)
print(array_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# ARRAY FILL WITH LINSPACE

In [25]:
array_lin=np.linspace(1,10,num=5)
print(array_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [26]:
arary_lin=np.linspace(2,10,num=5)
print(array_lin)

[ 1.    3.25  5.5   7.75 10.  ]
