In [1]:
import numpy as np

x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [2]:
y = [1,3,5,6]
print(y)

[1, 3, 5, 6]


In [3]:
print(type(x))

<class 'numpy.ndarray'>


# Creating NumPy Array

# To Create a NumPy array, you can use the function np.array().

In [4]:
a = [1,4,5,6,8]
a = np.array([1,4,5,6,8])
print(a)

[1 4 5 6 8]


# Data Type

In [5]:
y = [2,4,6,7]
y = np.array([2,4,6,7])
y

array([2, 4, 6, 7])

In [6]:
y = [2,4,6,7]
y = np.array([2,4,6,7])
print(type(y))

<class 'numpy.ndarray'>


# Types Of Array

# 1-D Array

In [7]:
arr= np.array([1,2,4,5])
print(arr)
print(type(arr))
print(arr.ndim)


[1 2 4 5]
<class 'numpy.ndarray'>
1


# 2-D Array

In [8]:
arr2 = np.array([[1,4,5,6],[6,7,8,9]])
print(arr2)
print(type(arr2))
print(arr2.ndim)

[[1 4 5 6]
 [6 7 8 9]]
<class 'numpy.ndarray'>
2


# 3-D Array

In [9]:
arr3 = np.array([[1,2,4,5],[7,8,9,0],[2,4,5,6]])
print(arr3)
print(type(arr3))
print(arr3.ndim)

[[1 2 4 5]
 [7 8 9 0]
 [2 4 5 6]]
<class 'numpy.ndarray'>
2


In [10]:
arn = np.array([2,4,5,6],ndim =10 )
print(arn)
print(arn.ndim)

TypeError: array() got an unexpected keyword argument 'ndim'