# Insert

In [1]:
import numpy as np
var = np.array([1,2,3,5])

print(var)
print()
v = np.insert(var,3,40)
print(v)

[1 2 3 5]

[ 1  2  3 40  5]


In [2]:
var1 = np.array([1,3,5,6,7,8,9])
print(var1)
print()
v1 = np.insert(var1, (1,4), 40)
print(v1)

[1 3 5 6 7 8 9]

[ 1 40  3  5  6 40  7  8  9]


In [3]:
var1 = np.array([1,3,5,6,7,8,9])
print(var1)
print()
v1 = np.insert(var1, (1,4), 2.2)
print(v1)

[1 3 5 6 7 8 9]

[1 2 3 5 6 2 7 8 9]


In [4]:
var2 = np.array([[1,2,3],[1,2,4]])
v2 = np.insert(var2, 2, 7, axis = 1)

print(var2)
print()
print(v2)

[[1 2 3]
 [1 2 4]]

[[1 2 7 3]
 [1 2 7 4]]


In [5]:
var2 = np.array([[1,2,3],[1,2,4]])
v2 = np.insert(var2, 2, 7, axis = 0)

print(var2)
print()
print(v2)

[[1 2 3]
 [1 2 4]]

[[1 2 3]
 [1 2 4]
 [7 7 7]]


In [7]:
var3 = np.array([[1,2,3],[1,2,4]])
v3 = np.insert(var3, 2, [22,23,24], axis = 0)

print(var3)
print()
print(v3)

[[1 2 3]
 [1 2 4]]

[[ 1  2  3]
 [ 1  2  4]
 [22 23 24]]


In [11]:
var4 = np.array([1,3,5,6,7,8,9])
print(var4)
print()
# v1 = np.insert(var1, (1,4), 2.2)
x = np.append(var1, 6.5) # To add the last digit using for append
print(x)

[1 3 5 6 7 8 9]

[1.  3.  5.  6.  7.  8.  9.  6.5]


In [17]:
var5 = np.array([[1,2,3,5],[6,8,9,7]])
# v1 = np.insert(var1, 2, [22,4,44], axis = 0)

v1 = np.append(var5,[[45,44,23,5]],axis=0)
print(v1)

[[ 1  2  3  5]
 [ 6  8  9  7]
 [45 44 23  5]]


# Delete

In [ ]:
var6 = np.array([1,3,4,5,6])
print(var6)
print