# Matrix

In [1]:
import numpy as np

var = np.matrix([[1,2,4],[1,2,4]])
print(var)
print(type(var))

[[1 2 4]
 [1 2 4]]
<class 'numpy.matrix'>


In [2]:
var1 = np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [11]:
var2 = np.matrix([[1,2],[1,4]])
var3 = np.matrix([[1,5],[3,5]])

print(var2 * var3)
print()
print(var2.dot(var3))

[[ 7 15]
 [13 25]]

[[ 7 15]
 [13 25]]


In [9]:
var4 = np.array([[1,2],[1,4]])
var5 = np.array([[1,5],[3,5]])

print(var4 * var5)


[[ 1 10]
 [ 3 20]]


# Matrix functions in NumPy Arrays

# Transpose
# Swapaxes
# Inverse
# Power
# Determinate

In [12]:
mtx = np.matrix([[1,2,3],[4,5,6]])
print(mtx)
print()
print(np.transpose(mtx)) # A = A^T

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [15]:
mtx1 = np.matrix([[1,3,4],[5,6,7]])
print(mtx1)
print()
print(np.swapaxes(mtx1, 0,1))

[[1 3 4]
 [5 6 7]]

[[1 5]
 [3 6]
 [4 7]]


In [16]:
mtx2 = np.matrix([[1,3],[5,6]])
print(mtx2)

print()
print(np.linalg.inv(var3)) # A-1

[[1 3]
 [5 6]]

[[-0.5  0.5]
 [ 0.3 -0.1]]


In [20]:
mtx3 = np.matrix([[1,2],[3,4]])
print(mtx3)
print()

print(np.linalg.matrix_power(mtx3,2))

print()
print(np.linalg.matrix_power(mtx3,0))

print()
print(np.linalg.matrix_power(var4,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 4.5  -2.5 ]
 [-1.25  0.75]]


In [21]:
mtx4 = np.matrix([[1,2],[3,4]])
print(mtx4)
print()
print(np.linalg.det(mtx4)) # deteminate values

[[1 2]
 [3 4]]

-2.0000000000000004


In [23]:
mtx5 = np.matrix([[1,2,3],[3,4,5],[1,2,3]])
print(mtx5)
print()
print(np.linalg.det(mtx5)) # two matrix same

[[1 2 3]
 [3 4 5]
 [1 2 3]]

0.0
