# Shape

In [1]:
import numpy as np

var = np.array([[1,2,3,4,5],[1,2,4,5,6]])
print(var)
print()
print(var.shape)

[[1 2 3 4 5]
 [1 2 4 5 6]]

(2, 5)


In [2]:
var1 = np.array([1,3,5,6],ndmin = 4)
print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 3 5 6]]]]
4

(1, 1, 1, 4)


# Reshape

In [11]:
var2 = np.array([2,4,5,7,4,9])
x = var2.reshape(3,2)
print(x)
print("Dimension: ",x.ndim)


[[2 4]
 [5 7]
 [4 9]]
Dimension:  2


In [12]:
var2 = np.array([2,4,5,7,4,9,4,5,6,7,8,9])
x = var2.reshape(2,3,2)
print(x)
print("Dimension: ",x.ndim)

[[[2 4]
  [5 7]
  [4 9]]

 [[4 5]
  [6 7]
  [8 9]]]
Dimension:  3
