# Zeros

In [1]:
import numpy as np

In [2]:
ar_zero = np.zeros(5)
print(ar_zero)

[0. 0. 0. 0. 0.]


In [3]:
ar_zero1 = np.zeros((3,4))
print(ar_zero1)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# ones

In [4]:
ar_one = np.ones(5)
print(ar_one)

[1. 1. 1. 1. 1.]


In [5]:
ar_one1 = np.ones((3,5))
print(ar_one1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Empty

In [6]:
ar_em = np.empty(4)
print(ar_em)

[2.12199579e-314 9.90972034e-312 6.48214127e-321 9.90972035e-312]


# Range Array

In [8]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


# Diagonal

In [10]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
ar_dia1 = np.eye(5,5)
print(ar_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Linspace

In [16]:
ar_lin = np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


In [19]:
ar_lin1 = np.linspace(0,20, num=5)
print(ar_lin1)

[ 1.          3.71428571  6.42857143  9.14285714 11.85714286 14.57142857
 17.28571429 20.        ]
